---
title: "ANA 515 Assignment 1"
author: "Clement Cheah"
date: '2022-06-04'
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(knitr)
library(bslib)
library(ggplot2)
```

```{r, echo=FALSE}
url <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
gunsdata<-read.csv(url)
```


```{r, include = FALSE}
library(dplyr)
youth <- gunsdata %>%
  filter (age <= 65)
```

```{r summary, include = FALSE}
guns_youth <- summary(youth)
print(guns_youth)
```

We have data about `r nrow(gunsdata)` individuals killed by guns.
Only `r nrow(gunsdata) - nrow(youth)` are older than 65.
The distribution of the remainder is shown below:


# Gun death by age
```{r youth-dist,echo=FALSE}
library(ggplot2)
youth %>%
  ggplot(aes(age)) + geom_freqpoly(binwidth=1)
```


#Gun deaths by race
```{r race-dist, echo=FALSE}
youth %>%
  ggplot(aes(fct_infreq(race) %>% fct_rev())) +
  geom_bar() + coord_flip() + 
  labs(x = "Victim Race")
```
```